export type ProductType = {
  id: number | string;
  name: string;
  image: string;
  price: number;
  rating?: number;
  ratingsCount?: number;
  categoryId: string;
  badgeIds?: string[];
  stock?: number;
  tags?: string[];
  description?: string;
  paymentMethods?: string[];
  shippingOptions?: import("./ShippingType").ShippingOptionType[];
  isDigital?: boolean;
  downloadUrl?: string;
  fileSize?: string; 
  fileFormat?: string; 
  pages?: number;
};
